#
# Finalize CI containers
#

ARG COMPILER
FROM add-python:$COMPILER

# Install additional tools
RUN apt-get update \
 && DEBIAN_FRONTEND=noninteractive apt-get --yes install --no-install-recommends \
      zstd \
 && rm -rf /var/lib/apt/lists/*
