ARG BASE
FROM $BASE
#
# Install netCDF C and Fortran libraries and their dependencies
#
ENV NCHOME=/home/runner/netcdf-c NFHOME=/home/runner/netcdf-fortran

# Install dependencies
RUN apt-get update && \
    apt-get -y install git m4 && \
    apt-get -y install libhdf5-dev libcurl4-gnutls-dev hdf5-helpers

# Need to use bash because the Intel compilers require setting
#   environment variables by sourcing a script
SHELL [ "/usr/bin/bash", "-c"]

# build netCDF C libraries
# Would be best to put the environment variables in the RUN but haven't figured
#   out how to do that with multiple variables
ENV CPPFLAGS=-I/usr/include/hdf5/serial \
    LDFLAGS=-L/usr/lib/x86_64-linux-gnu/hdf5/serial/
RUN source /opt/intel/oneapi/setvars.sh && \
    mkdir -p /source && \
    cd /source && \
    git clone https://github.com/Unidata/netcdf-c.git --branch v4.7.4 && \
    cd netcdf-c && \
    ./configure --prefix=${NCHOME} && \
    make -j && \
    make install && \
    make clean
ENV CPPFLAGS="" LDFLAGS=""
ENV LD_LIBRARY_PATH=${NCHOME}/lib
#
# netCDF Fortran libraries
#
ENV CPPFLAGS=-I${NCHOME}/include \
    LDFLAGS=-L${NCHOME}/lib \
    FCFLAGS=-fPIC
RUN source /opt/intel/oneapi/setvars.sh && \
    cd /source && \
    git clone https://github.com/Unidata/netcdf-fortran.git --branch v4.5.3 && \
    cd netcdf-fortran && \
    ./configure --prefix=${NFHOME} && \
    make -j && \
    make install && \
    make clean
ENV CPPFLAGS="" LDFLAGS=""
ENV LD_LIBRARY_PATH=${NFHOME}/lib:${LD_LIBRARY_PATH}
