FROM intel/oneapi-basekit:2023.2-devel-ubuntu22.04

# Extend and update the package registry
RUN apt-get update \
 && DEBIAN_FRONTEND=noninteractive apt-get --yes install --no-install-recommends \
      intel-oneapi-compiler-fortran \
 && rm -rf /var/lib/apt/lists/*

# Set default compiler executables
ENV FC=ifort CC=icc
