# FROM robertmpincus/ifort-netcdf
ARG BASE
FROM $BASE

RUN apt-get update && \
    apt-get -y install python3 python3-pip && \
    pip3 install urllib3 netcdf4 xarray dask scipy matplotlib seaborn colorcet && \
    apt install python-is-python3
