#
# Most current mix of compiler and single CUDA version available from
#   https://ngc.nvidia.com/catalog/containers/nvidia:nvhpc/tags
#
FROM nvcr.io/nvidia/nvhpc:22.9-devel-cuda11.7-ubuntu22.04

# Set default compiler executables
ENV FC=nvfortran CC=nvc
