#
# Most current mix of compiler and single CUDA version available from
#   https://ngc.nvidia.com/catalog/containers/nvidia:nvhpc/tags
#
FROM nvcr.io/nvidia/nvhpc:22.9-devel-cuda11.7-ubuntu22.04

RUN apt-get install zstd || true

ENV FC=nvfortran CC=nvc NVCOMPILERS=/opt/nvidia/hpc_sdk
ENV PATH=${NVCOMPILERS}/Linux_x86_64/22.9/compilers/bin:${PATH}
