#
# Install Python3 and a small set of packages
#

ARG COMPILER
FROM add-netcdf:$COMPILER

# Install Python
RUN apt-get update \
 && apt-get --yes install \
      --no-install-recommends \
      python-is-python3 \
      python3 \
      python3-pip

# Install essential packages
#   we install netCDF4 instead of xarray[io] to omit unnecessary packages
RUN pip3 install \
      dask[array] \
      netCDF4 \
      numpy \
      xarray

# Install packages for the validation plot generation
#   we install scipy instead of xarray[accel] to omit unnecessary packages
RUN pip3 install \
      colorcet \
      matplotlib \
      scipy \
      seaborn
