ARG COMPILER
FROM add-netcdf:$COMPILER
#
# Install Python3 and a small set of packages
#
RUN apt-get update && \
    apt-get -y install python3 python3-pip && \
    pip3 install urllib3 netcdf4 xarray dask scipy matplotlib seaborn colorcet && \
    apt install python-is-python3
